### ISSUE TITLE
List of needed terms for Biobanking use case

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/ancestro#2] opened 2017-02-15 11:29 UTC
From Chris Stoeckert, @cstoeckert:

For the Ontology for Biobanking project (http://obofoundry.org/ontology/obib.html), I have a need to capture the following in some way (used on a Consent and Enrollment form by a contributor):

The Jewish heritage category for a donor/participant on a caHUB study.
Ashkenazi Jewish
Sephardic Jewish
 	 
Candidate Ethnic Background (geographic)
Africa	 
 	Central African
 	North African
 	South African
Americas	 
 	African American
 	North American
 	Latin American
 	Caribbean
 	South American
Asia	 
 	Southeast Asian
 	South Asian
 	Central Asian
 	Chinese
 	Japanese
 	Indian
Australia/New Zealand	 
 	Australian
 	New Zealander
Europe	 
 	Eastern
 	Icelandic
 	Mediterranean
 	Scandinavian
 	Western European
 	Intercontinental
 	Middle Eastern
 	Hispanic

**Comment by cstoeckert** [comment] 2017-05-16 18:27
Hi All,
I need to address this now for a contract I'm working on. By importing terms from EFO and ERO under 'ethnic group', I can address about half of the above (see hierarchy below). However, I still need to address the following:
Central African
North African
South African
Southeast Asian
South Asian
Central Asian
Australia/New Zealand
Australian
New Zealander
Europe
Eastern European
Mediterranean
Scandinavian
Western European
Middle Eastern
Shall these be submitted to EFO to fit in the same way? How does Ancestro want to approach this? 
ethnic group
     African
     American
          African-American
          European-American
          Latino
               Latino, Carribean
               Latino, South American
     Ashkenazi Jew
     Asian
          Asian Indian
          Chinese
          Japanese
     Hispanic
     mixed ethnicity
     Nordic, Icelandic
     Sephardic Jew

**Comment by cstoeckert** [comment] 2017-05-16 18:38
Looks like the indents were lost. second try
ethnic group
-African
-American
--African-American
--European-American
--Latino
---Latino, Carribean
---Latino, South American
-Ashkenazi Jew
-Asian
--Asian Indian
--Chinese
--Japanese
-Hispanic
-mixed ethnicity
-Nordic, Icelandic
-Sephardic Jew

**Comment by daniwelter** [comment] 2017-05-17 15:58
Hi Chris,

We have most of these ancestral groups in ANCESTRO already and we should be able to create most of the ones that are missing (esp if you could supply us with definitions). Mixed ancestry is an ancestry status rather than an ancestral group. 
If adjustments to the hierarchy are required, I may have to negotiate this with our curators as ANCESTRO was designed specifically to meet the needs of GWAS ancestry recording. I'm sure we can figure something out though.

I'm just in the process of doing some refactoring of the ontology, including adding more definitions and migrating to a new URI schema so please be aware that the current URIs are not stable.

Thanks
Dani

**Comment by cstoeckert** [comment] 2017-05-17 19:41
Hi Dani,
Sounds good! Happy to work with you on this and come up with definitions. Is there a more recent version of ANCESTRO to look at than the one at Bioportal?  I did not see definitions there and got an error trying to load the owl files from https://github.com/EBISPOT/ancestro into Protege.
Also will you be reusing URIs from EFO or ERO for terms they have?
Thanks, Chris

**Comment by LLTommy** [comment] 2017-05-18 04:23
You could also try the version from [OLS](http://www.ebi.ac.uk/ols/ontologies/ancestro), it seems to be more recent. 

(Also I realised that bioportal links to dani's github as homepage (https://github.com/daniwelter/ancestro) rather than https://github.com/EBISPOT/ancestro)

**Comment by daniwelter** [comment] 2017-05-18 08:27
The version on Github is the latest version and it's also in OLS. What error did you get when trying to load the OWL files? I haven't committed the definitions back to Git yet - will try to do this by the end of the week.
The plan is for EFO to import ANCESTRO once the URIs are stable so there is no sense in importing EFO URIS. As I mentioned before, ANCESTRO was developed primarily to meet the needs of the GWAS Catalog and our curators had very specific requirements about how ancestral groups should be structured, which didn't quite fit the way ERO have done things, so we're not reusing their URIs at the moment.

**Comment by daniwelter** [comment] 2017-05-19 09:28
Hi Chris,
There's now a file on here called ancestro_refactored.owl. This will eventually replace ANCESTRO but I didn't want to overwrite the master with the new version until I'm happy with the edits. I wanted to get the changes out for users to see on here asap though, so feel free to have a look.
Thanks
Dani

**Comment by cstoeckert** [comment] 2017-05-19 17:27
Hi Dani,
Will do and give feedback with respect to this tracker request.
Thanks, Chris

**Comment by cstoeckert** [comment] 2017-05-22 15:22
Hi Dani,
Thank you for explaining the relationship with EFO. I’m uncertain as to whether the Ancestro terms will work for me.  A main question/ concern is understanding what is meant by ‘ancestral group’ as it is not defined (see also https://github.com/EBISPOT/ancestro/issues/3) and how it fits in the BFO/OBO hierarchy. Is it a ‘population’ http://purl.obolibrary.org/obo/OBI_0000181 ?. Or is it an ‘information content entity’ since mention of ‘not sufficient information’ is included in definitions of classes like Asian and African.
Thanks, Chris

**Comment by Public-Health-Bioinformatics** [comment] 2018-01-04 22:17
Hi, Dani,

I was just curious about how EFO symbiosis with Ancestro is going?  I'll try to synchronize how GenEpiO and FoodOn reference ethnicity through them after the honeymoon has been successful!

Cheers,

Damion

**Comment by daniwelter** [comment] 2018-01-05 15:37
Hi Damion,

I moved to the HCA project a few months ago and kinda dropped the ball on ancestro while I was wrapping up with GWAS and getting started with HCA. I'm moving back more into ontologies over the next few months so hopefully I'll be able to push ancestro over the line as part of this, especially as it's also needed for HCA.

Cheers
Dani

**Comment by daniwelter** [comment] 2019-07-22 13:46
Closing this issue as it has been dormant for over a year. Please note that ANCESTRO has  been deprecated in favour of HANCESTRO. The ontology is now at release 2.3, deployed in the OBO foundry and available via OLS. Additional documentation is available. Missing ancestry categories should be requested in separate tickets.

**Closed by daniwelter** 2019-07-22 13:46 UTC
